### ISSUE TITLE
1.0.2: pytest is failing because incorrect module name

### ISSUE THREAD

**Issue by kloczek** [ktosiek/pytest-vcr#50]
Generated .whl archive content
```console
Archive:  /home/tkloczko/rpmbuild/BUILD/pytest-vcr-1.0.2/dist/pytest_vcr-1.0.2-py2.py3-none-any.whl
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
    3143  Defl:N     1048  67% 04-26-2019 18:59 a1d2cfb9  pytest_vcr.py
    1082  Defl:N      646  40% 05-01-2022 13:40 1a51511f  pytest_vcr-1.0.2.dist-info/LICENSE
    2534  Defl:N      970  62% 05-01-2022 13:40 6d416547  pytest_vcr-1.0.2.dist-info/METADATA
     110  Defl:N       95  14% 05-01-2022 13:40 13a0f1ef  pytest_vcr-1.0.2.dist-info/WHEEL
      28  Defl:N       25  11% 05-01-2022 13:40 35064c9b  pytest_vcr-1.0.2.dist-info/entry_points.txt
      11  Defl:N       13 -18% 05-01-2022 13:40 a4d4d463  pytest_vcr-1.0.2.dist-info/top_level.txt
     570  Defl:N      345  40% 05-01-2022 13:40 bffe26cf  pytest_vcr-1.0.2.dist-info/RECORD
--------          -------  ---                            -------
    7478             3142  58%                            7 files
```
And pytest is failing becaue it cannot find `vcr` module name
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-pytest-vcr-1.0.2-12.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-pytest-vcr-1.0.2-12.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
Traceback (most recent call last):
  File "/usr/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 187, in console_main
    code = main()
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 145, in main
    config = _prepareconfig(args, plugins)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 324, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/usr/lib/python3.8/site-packages/_pytest/helpconfig.py", line 102, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/usr/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1016, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1304, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1187, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib64/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-pytest-vcr-1.0.2-12.fc35.x86_64/usr/lib/python3.8/site-packages/pytest_vcr.py", line 6, in <module>
    from vcr import VCR
ModuleNotFoundError: No module named 'vcr'
```

**Comment by kloczek** [comment]
Clodin. `vcr` looks like it is external module.
